"$schema" = "https://www.schemastore.org/bunfig.json"

[install]
auto = "disable"
linker = "isolated"
peer = false
minimumReleaseAge = 604800 # 7 days
minimumReleaseAgeExcludes = ["@maxmilton/*"]

[test]
preload = ["./test/setup.ts"]
