name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: packages/*/dist/**
          if-no-files-found: error
  test:
    needs: build
    name: test (node v${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [8, 10, 12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm@3
        if: ${{ matrix.node-version == 8 }}
      - run: npm install -g pnpm@5
        if: ${{ matrix.node-version == 10 }}
      - run: npm install --global pnpm
        if: ${{ matrix.node-version > 10 }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
        if: ${{ matrix.node-version >= 10 }}
      - run: pnpm run test-oldnode
        if: ${{ matrix.node-version < 10 }}
      - run: pnpm run test-nn
      - name: Report coverage
        if: ${{ matrix.node-version == 16 }}
        run: |
          curl -Lo ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
