name: ci
on: push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 16]
        platform: [ubuntu, windows, macos]
    name: test (node v${{ matrix.node-version }} ${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run test-raw
      - name: Report coverage
        if: ${{ matrix.node-version == 16 && matrix.platform == ubuntu }}
        run: |
          curl -Lo ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint
